### PR TITLE
Inline must_deserialize/may_deserialize and improve error message

### LINKED ISSUE #3: Provide better errors when failing to load storage Items
I have a set of contracts that use multiple `Item<String>`. Now I get the following error message:

> failed to execute message; message index: 0: dispatch: submessages: alloc::string::String not found: execute wasm contract failed: invalid request

Unfortunately this does not help much to locate the issue. `alloc::string::String` is the `type_name::<T>` in

```rust
/// must_deserialize parses json bytes from storage (Option), returning NotFound error if no data present
pub(crate) fn must_deserialize<T: DeserializeOwned>(value: &Option<Vec<u8>>) -> StdResult<T> {
    match value {
        Some(vec) => from_slice(vec),
        None => Err(StdError::not_found(type_name::<T>())),
    }
}
```

If I wasn't a core maintainer, the error message would be completety unreadable for me.

The error expresses that a key was not found and is emitted before trying to deserialize into any type. I think the key should become the main information in the error message. The type could be there too but maybe as an optional hint.

In order to address that, I think we should add a new error type to cosmwasm-std and deprecate `StdError::NotFound`.

### PR DESCRIPTION
**Pull request by webmaster128**
Closes #3

### CODE REVIEW

File: src/item.rs [hunk 1]
```diff
@@ -48,15 +48,19 @@ where
 
     /// load will return an error if no data is set at the given key, or on parse error
     pub fn load(&self, store: &dyn Storage) -> StdResult<T> {
-        let value = store.get(self.storage_key);
-        must_deserialize(&value)
+        if let Some(value) = store.get(self.storage_key) {
+            from_slice(&value)
+        } else {
+            let object_info = not_found_object_info::<T>(self.storage_key);
+            Err(StdError::not_found(object_info))
```
Comment (maurolacy) [inline src/item.rs:55]: 👍🏼 Nice improvement.

**Review by maurolacy — APPROVED** [review]
LGTM.
